name: tsms
description: "A new Flutter project."
 
 
publish_to: 'none'  
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  html: ^0.15.4
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
   
  flutter_lints: ^3.0.0

 
 

 
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animation/
    - assets/images/

   
   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
